### ISSUE TITLE
DB configuration per environment and several DB's per environment

### ISSUE THREAD

**Issue by leonpros** [zebrunner/carina-utils#15]
Since _config.properties allows to have different environment configurations, the _database.configuration should allow database configuration per environment as well.

Since each environment might have more that one database (might be different database types as well), the configurations should allow to configure as many connections as required per environment.

**Comment by zina-olson** [comment]
Adding to the @leonpros request, there can be multiple connections to the databases at the same time. It would be great to have a feature that supports adding configs for multiple DB connections at once within Carina Framework. For example, there can be a 2-5 different DB env, all must verify data existence in one and not in the other, and vice versa.
